/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


/**
 *
 * @author ME1
 */
class cadrast extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public cadrast() {
        initComponents();
        dataNascimentoTextField.setBackground(new java.awt.Color(0,0,0,1));
        cursoTextField.setBackground(new java.awt.Color(0,0,0,1));
        nomeTextField.setBackground(new java.awt.Color(0,0,0,1));
        serieTextField.setBackground(new java.awt.Color(0,0,0,1));
        
        


        // Add FocusListener to dataNascimentoTextField
        dataNascimentoTextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent evt) {
                if (dataNascimentoTextField.getText().isEmpty()) {
                    dataNascimentoLabel.setForeground(Color.RED);
                } else {
                    dataNascimentoLabel.setForeground(Color.GREEN);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dataNascimentoLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cursoLabel = new javax.swing.JLabel();
        serieLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        cursoTextField = new javax.swing.JTextField();
        serieTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dataNascimentoTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 118, 211));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Criado por Julio Cesar,Davi Lago ,Geovane Santos");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 360, 400, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transferir.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 440));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CADASTRO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 420, 41));

        nomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(199, 226, 255));
        nomeLabel.setText("Nome do aluno");
        jPanel2.add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 341, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_________________________________________");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 290, 39));

        dataNascimentoLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dataNascimentoLabel.setForeground(new java.awt.Color(199, 226, 255));
        dataNascimentoLabel.setText("Data de nascimento");
        jPanel2.add(dataNascimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_________________________________________");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 290, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 118, 211));
        jButton1.setText("CADASTRAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 341, 40));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_________________________________________");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 290, 40));

        cursoLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cursoLabel.setForeground(new java.awt.Color(199, 226, 255));
        cursoLabel.setText("Curso");
        jPanel2.add(cursoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, -1));

        serieLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        serieLabel.setForeground(new java.awt.Color(199, 226, 255));
        serieLabel.setText("Serie");
        jPanel2.add(serieLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 50, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("_________________________________________");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 290, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Premium Vector _ Cute panda holding bamboo with thumb up cartoon vector icon illustration animal nature isolated.jpeg.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 290, 260));

        nomeTextField.setFont(nomeTextField.getFont().deriveFont(nomeTextField.getFont().getSize()+2f));
        nomeTextField.setForeground(new java.awt.Color(255, 255, 255));
        nomeTextField.setBorder(null);
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        nomeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeTextFieldKeyPressed(evt);
            }
        });
        jPanel2.add(nomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, 30));

        cursoTextField.setFont(cursoTextField.getFont().deriveFont(cursoTextField.getFont().getSize()+2f));
        cursoTextField.setForeground(new java.awt.Color(255, 255, 255));
        cursoTextField.setBorder(null);
        cursoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoTextFieldActionPerformed(evt);
            }
        });
        cursoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cursoTextFieldKeyPressed(evt);
            }
        });
        jPanel2.add(cursoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, 30));

        serieTextField.setFont(serieTextField.getFont().deriveFont(serieTextField.getFont().getSize()+2f));
        serieTextField.setForeground(new java.awt.Color(255, 255, 255));
        serieTextField.setBorder(null);
        serieTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieTextFieldActionPerformed(evt);
            }
        });
        serieTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serieTextFieldKeyPressed(evt);
            }
        });
        jPanel2.add(serieTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 20, 30));

        dataNascimentoTextField.setBorder(null);
        dataNascimentoTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            dataNascimentoTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataNascimentoTextFieldFocusLost(evt);
            }
        });
        dataNascimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(dataNascimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 240, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 600, 440));

        setSize(new java.awt.Dimension(916, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String serie = serieTextField.getText();
     String nome = nomeTextField.getText();
     String curso = cursoTextField.getText();
     String dataNascimento = dataNascimentoTextField.getText();
      if (serie.isEmpty() || nome.isEmpty() || curso.isEmpty() || dataNascimento.isEmpty()) {
       
        if (serie.isEmpty()) {
            serieLabel.setForeground(Color.RED);
        } else {
            serieLabel.setForeground(Color.GREEN);
        }
        if (nome.isEmpty()) {
            nomeLabel.setForeground(Color.RED);
        } else {
            nomeLabel.setForeground(Color.GREEN);
        }
        if (curso.isEmpty()) {
            cursoLabel.setForeground(Color.RED);
        } else {
            cursoLabel.setForeground(Color.GREEN);
        }
        if (dataNascimento.isEmpty()) {
            dataNascimentoLabel.setForeground(Color.RED);
        } else {
            dataNascimentoLabel.setForeground(Color.GREEN);
        }
        
        
        // Retornar sem realizar o cadastro
        return;
    } 
     
     LocalDate dataNasc = LocalDate.parse(dataNascimento, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
     LocalDate hoje = LocalDate.now();
     Period periodo = Period.between(dataNasc, hoje);
     int idade = periodo.getYears();
     
     if (idade < 18) {
         String responsavel = JOptionPane.showInputDialog(this, "Informe o nome do responsável:");
         if (responsavel != null && !responsavel.isEmpty()) {
             ExibirDadosFrame ExibirDadosFrame = new ExibirDadosFrame();
             ExibirDadosFrame.setDados(nome, serie, curso, dataNascimento, responsavel);
             ExibirDadosFrame.setVisible(true);
         }
     } else {
         ExibirDadosFrame ExibirDadosFrame = new ExibirDadosFrame();
         ExibirDadosFrame.setDados(nome, serie, curso, dataNascimento, "Maior de Idade");
         ExibirDadosFrame.setVisible(true);
     }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cursoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoTextFieldActionPerformed

    private void serieTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serieTextFieldActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void nomeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextFieldKeyPressed
           if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           cursoTextField.requestFocus();
           }
    }//GEN-LAST:event_nomeTextFieldKeyPressed

    private void cursoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cursoTextFieldKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           serieTextField.requestFocus();}   
    }//GEN-LAST:event_cursoTextFieldKeyPressed

    private void serieTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serieTextFieldKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           dataNascimentoTextField.requestFocus();}
    }//GEN-LAST:event_serieTextFieldKeyPressed

    private void dataNascimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoTextFieldActionPerformed

    private void dataNascimentoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoTextFieldFocusLost

    }//GEN-LAST:event_dataNascimentoTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadrast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadrast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadrast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadrast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new cadrast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cursoLabel;
    private javax.swing.JTextField cursoTextField;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JFormattedTextField dataNascimentoTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel serieLabel;
    private javax.swing.JTextField serieTextField;
    // End of variables declaration//GEN-END:variables
}
